name: Metadata Action Test

on:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    name: release

    steps:
      - uses: radcortez/project-metadata-action@main
        name: retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'
